chore(travis): Another go

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,13 +6,14 @@ node_js:
 services:
   - mongodb
 env:
-  - MONGO_CONNECTION_STRING="mongodb://localhost/test"
+  - MONGO_CONNECTION_STRING="mongodb://test:test@localhost/test"
 before_script:
-    - |
-      echo "Testing MongoDB connection...";tries=4;
-      i=0;
-      while [ $i -lt $tries ]; do fail=$(mongo --eval db 2>&1 >/dev/null | grep "connect failed");
-        if [ "$fail" ] && [ $[ $i+1 ] -eq $tries ] ; then echo "Error: Could not connect to mongodb"; exit 1;
-        elif [ "$fail" ]; then sleep 3; i=$[ $i+1 ];
-        else echo "OK"; i=$tries; fi;
-      done
+  - |
+    echo "Testing MongoDB connection...";tries=4;
+    i=0;
+    while [ $i -lt $tries ]; do fail=$(mongo --eval db 2>&1 >/dev/null | grep "connect failed");
+      if [ "$fail" ] && [ $[ $i+1 ] -eq $tries ] ; then echo "Error: Could not connect to mongodb"; exit 1;
+      elif [ "$fail" ]; then sleep 3; i=$[ $i+1 ];
+      else echo "OK"; i=$tries; fi;
+    done
+  - "mongo test --eval 'db.addUser("test", "test");'"
